export const configOxlint = [
	// eslint
	{
		rules: {
			'class-methods-use-this': 'off',
			'default-case': 'off',
			'for-direction': 'off',
			'no-alert': 'off',
			'no-async-promise-executor': 'off',
			'no-await-in-loop': 'off',
			'no-bitwise': 'off',
			'no-caller': 'off',
			'no-console': 'off',
			'no-constant-condition': 'off',
			'no-empty-function': 'off',
			'no-fallthrough': 'off',
			'no-restricted-globals': 'off',
			'no-restricted-properties': 'off',
			'no-restricted-syntax': 'off',
			'no-unused-vars': 'off',
			'no-useless-backreference': 'off',
			'no-useless-call': 'off',
			'no-useless-catch': 'off',
			'no-useless-computed-key': 'off',
			'no-useless-concat': 'off',
			'no-useless-constructor': 'off',
			'no-useless-escape': 'off',
			'no-useless-rename': 'off',
			'no-var': 'off',
			'no-void': 'off',
			'no-warning-comments': 'off',
			'operator-assignment': 'off',
			'prefer-destructuring': 'off',
			'prefer-exponentiation-operator': 'off',
			'prefer-numeric-literals': 'off',
			'prefer-object-has-own': 'off',
			'prefer-object-spread': 'off',
			'prefer-promise-reject-errors': 'off',
			'prefer-rest-params': 'off',
			'prefer-spread': 'off',
			radix: 'off',
			'require-await': 'off',
			'require-yield': 'off',
			'symbol-description': 'off',
			'use-isnan': 'off',
			'valid-typeof': 'off',
			yoda: 'off',
		},
	},
	// promise
	{
		rules: {
			// 'promise/always-return': 'off', // bugged in oxlint
			// 'promise/catch-or-return': 'off', // bugged in oxlint
			'promise/no-callback-in-promise': 'off',
			'promise/no-new-statics': 'off',
			'promise/no-promise-in-callback': 'off',
			'promise/no-return-wrap': 'off',
			'promise/no-nesting': 'off',
			'promise/param-names': 'off',
			'promise/valid-params': 'off',
		},
	},
	// tseslint
	{
		rules: {
			'@typescript-eslint/explicit-function-return-type': 'off',
			'@typescript-eslint/no-empty-object-type': 'off',
			'@typescript-eslint/no-explicit-any': 'off',
			'@typescript-eslint/no-floating-promises': 'off', // FIXME: wait for oxlint to enable type-aware linting by default
			'@typescript-eslint/no-misused-promises': 'off', // FIXME: wait for oxlint to enable type-aware linting by default
			'@typescript-eslint/no-restricted-types': 'off',
			'@typescript-eslint/no-unnecessary-type-assertion': 'off', // FIXME: wait for oxlint to enable type-aware linting by default
			'@typescript-eslint/no-unsafe-function-type': 'off',
			'@typescript-eslint/no-unused-vars': 'off',
			'@typescript-eslint/no-wrapper-object-types': 'off',
		},
	},
	// unicorn
	{
		rules: {
			'unicorn/catch-error-name': 'off',
			'unicorn/consistent-assert': 'off',
			'unicorn/consistent-date-clone': 'off',
			'unicorn/consistent-empty-array-spread': 'off',
			'unicorn/consistent-existence-index-check': 'off',
			'unicorn/consistent-function-scoping': 'off',
			'unicorn/empty-brace-spaces': 'off',
			'unicorn/error-message': 'off',
			'unicorn/escape-case': 'off',
			'unicorn/explicit-length-check': 'off',
			'unicorn/filename-case': 'off',
			'unicorn/new-for-builtins': 'off',
			'unicorn/no-abusive-eslint-disable': 'off',
			'unicorn/no-accessor-recursion': 'off',
			'unicorn/no-anonymous-default-export': 'off',
			'unicorn/no-array-callback-reference': 'off',
			'unicorn/no-array-for-each': 'off',
			'unicorn/no-array-method-this-argument': 'off',
			'unicorn/no-array-reduce': 'off',
			'unicorn/no-array-reverse': 'off',
			'unicorn/no-array-sort': 'off',
			'unicorn/no-await-expression-member': 'off',
			'unicorn/no-await-in-promise-methods': 'off',
			'unicorn/no-console-spaces': 'off',
			'unicorn/no-document-cookie': 'off',
			'unicorn/no-empty-file': 'off',
			'unicorn/no-for-loop': 'off',
			'unicorn/no-hex-escape': 'off',
			'unicorn/no-instanceof-builtins': 'off',
			'unicorn/no-invalid-fetch-options': 'off',
			'unicorn/no-invalid-remove-event-listener': 'off',
			'unicorn/no-lonely-if': 'off',
			'unicorn/no-magic-array-flat-depth': 'off',
			'unicorn/no-negated-condition': 'off',
			'unicorn/no-negation-in-equality-check': 'off',
			'unicorn/no-nested-ternary': 'off',
			'unicorn/no-new-array': 'off',
			'unicorn/no-new-buffer': 'off',
			'unicorn/no-null': 'off',
			'unicorn/no-object-as-default-parameter': 'off',
			'unicorn/no-process-exit': 'off',
			'unicorn/no-single-promise-in-promise-methods': 'off',
			'unicorn/no-static-only-class': 'off',
			'unicorn/no-thenable': 'off',
			'unicorn/no-this-assignment': 'off',
			'unicorn/no-typeof-undefined': 'off',
			'unicorn/no-unnecessary-array-flat-depth': 'off',
			'unicorn/no-unnecessary-array-splice-count': 'off',
			'unicorn/no-unnecessary-await': 'off',
			'unicorn/no-unnecessary-slice-end': 'off',
			'unicorn/no-unreadable-array-destructuring': 'off',
			'unicorn/no-unreadable-iife': 'off',
			'unicorn/no-useless-error-capture-stack-trace': 'off',
			'unicorn/no-useless-fallback-in-spread': 'off',
			'unicorn/no-useless-length-check': 'off',
			'unicorn/no-useless-promise-resolve-reject': 'off',
			'unicorn/no-useless-spread': 'off',
			'unicorn/no-useless-switch-case': 'off',
			'unicorn/no-useless-undefined': 'off',
			'unicorn/no-zero-fractions': 'off',
			'unicorn/number-literal-case': 'off',
			'unicorn/numeric-separators-style': 'off',
			'unicorn/prefer-add-event-listener': 'off',
			'unicorn/prefer-array-find': 'off',
			'unicorn/prefer-array-flat': 'off',
			'unicorn/prefer-array-flat-map': 'off',
			'unicorn/prefer-array-index-of': 'off',
			'unicorn/prefer-array-some': 'off',
			'unicorn/prefer-at': 'off',
			'unicorn/prefer-blob-reading-methods': 'off',
			'unicorn/prefer-class-fields': 'off',
			'unicorn/prefer-classlist-toggle': 'off',
			'unicorn/prefer-code-point': 'off',
			'unicorn/prefer-date-now': 'off',
			'unicorn/prefer-dom-node-append': 'off',
			'unicorn/prefer-dom-node-dataset': 'off',
			'unicorn/prefer-dom-node-remove': 'off',
			'unicorn/prefer-dom-node-text-content': 'off',
			'unicorn/prefer-event-target': 'off',
			'unicorn/prefer-global-this': 'off',
			'unicorn/prefer-includes': 'off',
			'unicorn/prefer-logical-operator-over-ternary': 'off',
			'unicorn/prefer-math-min-max': 'off',
			'unicorn/prefer-math-trunc': 'off',
			'unicorn/prefer-modern-dom-apis': 'off',
			'unicorn/prefer-modern-math-apis': 'off',
			'unicorn/prefer-native-coercion-functions': 'off',
			'unicorn/prefer-negative-index': 'off',
			'unicorn/prefer-node-protocol': 'off',
			'unicorn/prefer-number-properties': 'off',
			'unicorn/prefer-object-from-entries': 'off',
			'unicorn/prefer-optional-catch-binding': 'off',
			'unicorn/prefer-prototype-methods': 'off',
			'unicorn/prefer-query-selector': 'off',
			'unicorn/prefer-reflect-apply': 'off',
			'unicorn/prefer-regexp-test': 'off',
			'unicorn/prefer-set-has': 'off',
			'unicorn/prefer-set-size': 'off',
			'unicorn/prefer-spread': 'off',
			'unicorn/prefer-string-raw': 'off',
			'unicorn/prefer-string-replace-all': 'off',
			'unicorn/prefer-string-slice': 'off',
			'unicorn/prefer-string-starts-ends-with': 'off',
			'unicorn/prefer-string-trim-start-end': 'off',
			'unicorn/prefer-structured-clone': 'off',
			'unicorn/prefer-top-level-await': 'off',
			'unicorn/prefer-type-error': 'off',
			'unicorn/require-array-join-separator': 'off',
			'unicorn/require-module-specifiers': 'off',
			'unicorn/require-number-to-fixed-digits-argument': 'off',
			'unicorn/switch-case-braces': 'off',
			'unicorn/text-encoding-identifier-case': 'off',
			'unicorn/throw-new-error': 'off',
		},
	},
];
